#!/bin/sh
#
# Script to install manualy Extra OS Templates after new installation
# Author dterweij
#
startopenvz() {
mkdir -p /vz/template/cache
cd /vz/template/cache/
wget -nd -np -c -r download.lxcenter.org/download/vpstemplate/base/
}
#
startxen() {
mkdir -p /home/hypervm/xen/template/
cd /home/hypervm/xen/template/
wget -nd -np -c -r download.lxcenter.org/download/vmtemplate/base/
}
#
# Check how we were called.
#
case "$1" in
  --xen)
    startxen
    ;;
  --openvz)
    startopenvz
    ;;
  *)
   	echo $"Install extra OSTemplates"
    	echo $"The usage is:"
    	echo $"sh $0 --xen (To install Xen templates)"
    	echo $"sh $0 --openvz (To install OpenVZ templates)"
	exit 1
esac
exit $?
#
# End