<?php
/*
 *    HyperVM, Server Virtualization GUI for OpenVZ and Xen
 *
 *    Copyright (C) 2000-2009    LxLabs
 *    Copyright (C) 2009-2012    LxCenter
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * $id: massagelib.php
 * $version: HyperVM Dutch (NL) 2.1.X
 * $translated by: Gerard van der Vegt
 * $last update: 2 maart 2012
*/

$__information['ndskshortcut_list__pre'] = "Het is mogelijk om in Kloxo favorieten toe te voegen door op de link [b] toevoegen aan favorieten [/b] te klikken die rechts bovenaan elke pagina staat. Elke snelkoppeling krijgt de parameter met de naam [b] volgorde-id [/b]. Na het toevoegen van de snelkoppeling kan er bij het [b] bewerken van favorieten [/b] de volgorde worden aangepast. Door op elke snelkoppeling een geschikt [b] volorde-id [/b] toe te passen, kunt u de lijst op elke gewenste manier ordenen. Ook de naam van de link kan aangepast worden naar een meer persoonlijk herkenbare naam. De werkelijke favorieten lijst op het linkerpaneel zal precies de volgorde weerspiegelen die hier zichtbaar is.";
// You can add a page in kloxo to the favorites, by clicking on the [b] add to favorites [/b] link on [b] that particular page. [/b] Each shortcut has a parameter called [b] Sort Id [/b]. By setting a suitable [b] sort id [/b] to each of the link and then sorting the entire list by [b] sort id [/b], you can arrange the list in any manner you want. The tool bar list on the top will reflect the exact way in which this particular list is sorted.
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "Hiermee zal een LXlabs SSH sleutel worden toegevoegd aan je geautoriseerde sleutels, waarmee je LXlabs support personeel toe laat om zonder wachtwoord in te loggen op je server. Het is aangeraden om dit te doen wanneer je hebt aangegeven assistentie te willen van LXlabs"; 
// This will add lxlabs ssh key to your authorized keys, which will allow lxlabs support personnel to login to your server without password. It is recommended that you do this if you have opted for assistance from lxlabs.
$__information['rawlxguardhit_list__pre'] = "Dit is de lijst van ruwe verbindingen. Dit is vooral handig om een ip-adres te traceren als u gebruikers account weet. Bijvoorbeeld, wanner uw eigen klanten proberen in te loggen op de server. Wanneer dit te vaak geprobeerd word, dan worden ze geblokkerd. Op deze pagina kan je [b] geavanceerd zoeken [/ b] waarmee je op gebruikerslogin [b] [/ b] kan zoeken. Hiermee kan je het ip-adres van de klant vinden zodat je deze kan verwijderen van de hoofd verbindingen pagina."; 
// This is the list of raw connections. This is primarily useful to trace an IP if you know the useraccount. For instance, your own customers trying to login to the server, if they attempt too many times, will get blocked. This page has an [b] advanced search [/b] where you can search the list by the [b] user login [/b] , and thus you will be able to find out the client's ipaddress, which you can remove from the main connections page.
$__information['login_pre'] = "<p> Welkom bij <%programname%>  </p><p>Gebruik een geldig gebruikersnaam en wachtwoord om toegang te krijgen tot de console. </p>"; 
// <p> Welcome to <%programname%>  </p><p>Use a valid username and password to gain access to the console. </p> 
$__information['tickethistory_addform__pre'] = "Om tekst te citeren kunt u &#91quote&#93 &#91/quote &#93 gebruiken. U kunt &#91code&#93 &#91/code&#93 gebruiken voor codefragmenten, en &#91b&#93 &#91/b&#93 voor vette tekst."; 
// You can use &#91quote&#93 &#91/quote &#93 to quote some text, which will shown properly formatted. You can also use &#91code&#93 &#91/code&#93 for code snippets, and &#91b&#93 &#91/b&#93 for bold.
$__information['lxguardwhitelist_addform__pre'] = "Het is aanbevolen dat u de knop [b] witte lijst [/b] bovenaan de <url:a=list&c=lxguardhitdisplay>verbindingen pagina</url> gebruikt om een ip-adres aan de witte lijst toe te voegen. Het handmatig invoeren van ip-adressen kan leiden tot spelfouten en verwarring. Doe een dubbele controle wanneer u hier een ip-adres invoert "; 
// It is recommended that you use the [b] whitelist [/b] button on top of the <url:a=list&c=lxguardhitdisplay>Connections Page</url>, to whitelist an Ipaddress. Manually entering the IP is bound to lead to spelling mistakes, and you will be left confused. If you are entering your IP here, please double check that it is correct.
$__information['sshconfig_updateform_update_pre'] = "Het is aanbevolen dat u volledig wachtwoord gebaseerde toegang tot deze server uitschakeld en in plaats daarvan de <url:goback=1&a=list&c=sshauthorizedkey>ssh sleutel verificatiebeheer</url> gebruikt om specifieke mensen toegang te geven zonder wachtwoord. Als dit hyperVM is en u van plan bent om VPS's te verkopen aan andere mensen, dan is het niet mogelijk om SSH wachtwoord toegang uit te schakelen. Dit is omdat vps-eigenaren moeten inloggen met het knooppunt om toegang te krijgen tot hun consoles. Zorg er in ieder geval voor dat wachtwoord gebaseerde toegang tot deze server uitschakeld is.<br> Dus als vaste regel op kloxo; schakel wachtwoord toegang tot alles uit, terwijl op hyperVM alleen wachtwoord toegang tot root wordt uitgeschakeld."; 
// It is recommended that you completely disable password based access to this server, and instead use the  <url:goback=1&a=list&c=sshauthorizedkey>ssh authorization key manager </url> to allow specific people to access without password. If this is hyperVM, and you are intending to sell VPSes to other people, you won't be able to completely disable ssh password access, since vps-owners will need to login the node to access their consoles. In any case, make sure you disable password based root access to this server. So as a rule of thumb, on kloxo, disable password access to everything, while on hyperVM, disable password access to root alone.
$__information['all_dns_list__pre'] = "Dit is de lijst van elke DNS aangemaakt door VP eigenaren. <url:o=general&a=updateform&sa=reversedns>Klik hier</url> om DNS servers te configureren zodat alle klanten hier gebruik van kunnen maken. Het DNS beheer van HyperVm staat toe dat een VPS eigenaar een DNS in HyperVm kan aanmaken. De data wordt opgeslagen op de VPS verkoper server. Met andere woorden; het is toegstaan om de VPS klanten DNS te hosten op uw servers";
// This is the list of every dns created by your VPS owners. <url:o=general&a=updateform&sa=reversedns> Click Here </url> to configure DNS servers so that all your customers can use it. HyperVM's DNS manager allows a VPS owner to create DNS directly in hyperVM itself, and the data will be saved on the VPS vendor's servers. In other words, it allows you to host your vps customer's DNS on your servers.
$__information['actionlog_list__pre'] = "Actie Rapporten registreren alle acties uitgevoerd op een account of VPS. Het belangrijkste dat moet worden opgemerkt is dat de reserve-id van de persoon die is ingelogd hier naar behoren is geregistreerd. Geef dus nooit de inloggegevens van het hoofd account aan iemand. In plaats daarvan maak een <url:a=list&c=auxiliary>reserve identiteit</url> voor elke lid van uw organisatie."; 
// Action log records all the actions executed on a client or a vps. The important thing you should note is that the auxiliary id of the person logged in is properly recorded here. So you should never give out the main account to anyone, instead create <url:a=list&c=auxiliary> auxiliary identities </url>for each of your staff.
$__information['sshauthorizedkey_list__pre'] = "[b]Let op[/b]: Het bestand ~/.ssh/authorized_keys2 is afgekeurd als openssh versie 3, dus wordt alleen het ~/.ssh/authorized_keys bestand beheerd. Dit zijn de ssh sleutels van de machines die op deze server kunnen inloggen zonder wachtwoord. Zorg ervoor dat u deze lijst kort houdt."; 
// Please note, the ~/.ssh/authorized_keys2 file has been deprecated as of openssh version 3, and so only the ~/.ssh/authorized_keys file is managed. These are the ssh keys from the machines which can login to this server without providing password. Make sure you keep this list trimmed.
$__information['updateform_forcedeletepserver_pre'] = "De server geforceerd verwijderen verwijderdt de server van de hyperVM database. Dit is nuttig als de server volledig is verwijderd en niet langer toegankelijk is."; 
// Force delete Server just removes the server from hyperVM's database. This is useful if the server has been completely removed is no longer accessible.
$__information['allowedip_addform__pre'] = "[b]Let op[/b]: Deze blokkering is alleen bedoeld voor het blokkeren van de toegang naar het controle paneel en zal dus niet de toegang blokkeren naar de bron. U kunt een ip-adres in de vorm [b] 192.168.1.*[/b] invoeren om een bereik aan te geven. Dat wil zeggen dat in plaats van een nummer er een [b]*[/b] gebruikt kan worden voor het gehele bereik. Het is ook mogelijk om afzonderlijke ip-adressen in de vorm van 192.168.1.2 toe te voegen. Houd er rekening mee dat de decimale notatie noodzakelijk is en alle vier de velden ingevuld moeten worden. Wanneer iedereen wordt toegestaan verwijder dan alle toegestane ip-adressen of vul de velden in met [b]*. *. *. *[/b]. Andere ip-notaties worden op dit moment niet ondersteund."; 
// Please note: This is only meant for blocking access to the control panel, and will not block access to the actual resource. You can add an ip of the form [b] 192.168.1.*[/b]  denote a range. That is, instead of providing a number, you can use [b] * [/b]  to represent the entire range. You can also add individual ips of the form 192.168.1.2. Please note that the dotted notation is necessary, and you have to provide all the 4 fields. If you want to allow everyone, remove all the allowed ips, or provide [b] *.*.*.* [/b]. Other IP notations are not supported at this point.
$__information['blockedip_addform__pre'] = "[b]Let op[/b]: Deze blokkering is alleen bedoeld voor het blokkeren van de toegang naar het controle paneel en zal dus niet de toegang blokkeren naar de bron. Dit is de lijst van geblokkeerde ip-adressen. De ip-notatie is hetzelfde als dat van toegestane ip. Alleen als de toegestane ip-lijst leeg is zullen de geblokkeerde ip-adressen moeten worden toegevoegd. Als de toegestane ip-lijst niet leeg is dan worden automatisch alle ip-adressen die niet vermeld staan geweigerd."; 
// Please note: This is only meant for blocking access to the control panel, and will not block access to the actual resource. This is the list of blocked ipaddresses. The ip notation is the same as that of allowed ip. You should add blocked ips only if the allowed ip list is empty. If allowed ip list is non-empty then, automatically all ips not listed are denied.
$__information['updateform_portconfig_pre'] = "Deze pagina is voornamelijk bedoeld om de poorten van Kloxo/HyperVM configureren. Na het maken van veranderingen zal Kloxo/HyperVM opnieuw opgestart moeten worden om de wijzigingen door te voeren.<br> Voer deze opdracht uit [b]cd /usr/local/lxlabs/<%program%>/httpdocs; lphp.exe.../bin/common/misc/defaultport.php[/b] om de poorten in te stellen op de standaardwaarde. Vervolgen Kloxo/HyperVm opnieuw opstarten. Laat de velden leeg om terug te keren naar de standaard poorten."; 
// This page is primarily meant to configure the ports of Kloxo/HyperVM. After making the changes here, you will need to restart Kloxo/HyperVM service once for the changes to take effect. Run this command [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b] and the ports will be reset to the default. You can then restart Kloxo/HyperVM. Leave the fields blank to revert to default ports.
$__information['updateform_schedule_conf_pre'] = "[b]Let op[/b]: Alleen de geplande back-ups die beginnen met de naam <%program%>-scheduled- zullen worden gedraaid. Wanneer er een backup met eigen naam gemaakt wordt dan zal deze niet mee draaien. Gebruik bij het maken van een handmatige backup de eerste tekenreeks als [b] <%program%>-scheduled-[/b] om de backup mee te laten draaien."; 
// Please note that only the scheduled backups, that is, backups that start with the name <%program%>-scheduled-, will be rotated. If you create your own backup with your own name, they won't be rotated. So if you want a manually created backup to be rotated, provide the initial string as [b] <%program%>-scheduled- [/b]
$__information['updateform_ssl_kloxo_pre'] = "Hiermee word het ssl-certificaat voor <%program%> ingesteld als deze bepaald certificaat. Zorg ervoor dat u <%program%> opnieuw opstart nadat het hier ingesteld is."; 
// This will set the ssl certificate for <%program%> as this particular certificate. Make sure you restart <%program%> after you set it here.
$__information['updateform_ssl_authorized_keys_pre'] = "Dit zijn de SSH sleutels van de machines die op uw account mogen inloggen zonder wachtwoord te gebruiken. Er wordt &euml;&eumln sleutel per regel bewaard. Je kan de sleutels toewijzen aan de machines die zonder wachtwoord mogen inloggen. Ook moet je dit bestand kort houden om de kans op ongewenst inloggen te verminderen."; 
// These are the SSH keys from the machines which are authorized to login to your account without supplying the password. They are kept as 1 per line. You can add the keys to the machines you want to have password-less access to this machine. You should also keep this file trimmed so as to reduce the chances of unwanted people logging in
$__information['updateform_ssl_hypervm_pre'] = "Hiermee word het ssl-certificaat voor <%program%> ingesteld als deze bepaald certificaat. Zorg ervoor dat u <%program%> opnieuw opstart nadat het hier ingesteld is."; 
// This will set the ssl certificate for <%program%> as this particular certificate. Make sure you restart <%program%> after you set it here.
$__information['updateform_selfbackupconfig_pre'] = "Dit is voornamelijk bedoeld voor het configureren van de externe back-up van de master-database, en niets anders. De database dump dagelijks wordt genomen en wordt opgeslagen in een lokale map in deze machine. Als een FTP-account hier is geconfigureerd, zal het bestand worden ge�pload naar de machine. Dit is voornamelijk handig in grote clusterinstallatie waar het falen van meester veel grotere gevolgen kan hebben."; 
// This is primarily meant to configure the remote backup of the master database and nothing else. The database dump is taken everyday and is saved in a local folder in this machine. If an ftp account is configured here, the file will be uploaded to the machine. This is mainly useful in large cluster setup where the failure of master can have much larger impacts.
$__information['lxguard_updateform_update_pre'] = "LXguard zorgt voor bescherming tegen aanvallen van buitenaf door toezicht van de ssh en FTP logboek berichten en door ip-adressen te blokkeren die te veel mislukte inlog pogingen hebben gedaan op de server. LXguard staat standaard ingeschakeld en zal automatisch hosts blokkeren. LXguard kan niet worden uitgeschakeld. Door een drempel [b]van mislukte pogingen[/b] op te geven of door bepaalde ip-adressen aan de witte lijst toe te voegen kan LXguard worden geconfigureerd. Wanneer een IP-adres word gevonden in de witte lijst dan zal het niet worden geblokkeerd. Het ip-adres word dan niet geblokkeerd wanneer het de drempel vanmislukte pogingen heeft overschreden. Om de waarschuwingen niet meer te laten verschijnen verwijderen dient bij onderstaande overeenkomst de checkbox aangevinkt te worden."; 
// Lxguard protects you against brute force attacks by monitoring the ssh and ftp log messages, and blocking ipaddresses that have too many failed attempts at logging into the server. Lxguard is default turned on, and will automatically block hosts, and cannot be turned off. You can configure Lxguard by specifying the [b] threshold of failed attempts [/b] or by adding certain ipaddresses to the whitelist. If an IP is found in the whitelist, it won't be blocked, even if it has crossed the threshold of failed attempts. To remove the warnings you get about Lxguard please click on the agreement checkbox below
$__information['updateform_generalsetting_pre'] = "De 'HelpDesk URL' is een link naar uw Helpdesk die gebruikt word in plaats van de standaard helpdesk die is ingebouwd in de software. De 'gemeenschaps URL' is de link die de klant ziet aan de linker kant op zijn pagina en in normale gevallen kan verwijzen naar uw forum."; 
// The 'HelpDesk Url' is a link to your Helpdesk, which will be used in place of the default help desk built into the software. Community Url is the link the client will see on his left page, and in normal cases can point to your forum.
$__information['custombutton_addform__pre'] = "In de URL kan er %nname% gebruikt worden die dan zal worden vervangen door de naam van de klant. Alleen voor Kloxo kan er %default_domain% gebruikt worden voor het standaarddomein van de klant."; 
// In the url, you can use %nname%, which will be substituted with the name of the client. For Kloxo only, you can use %default_domain% for the default domain of the client.
$__information['updateform_download_config_pre'] = "Normaal gesproken wanneer er bestanden gedownload worden dan maakt de master een tijdelijke sessie aan en wordt de browser vervolgens rechtstreeks omgeleid naar de slave. Dit is om bandbreedte te besparen, omdat anders de bestanden onnodig via de master moeten gaan. Als u dit inschakelt zal hyperVM en meteen voor zorgen in plaats van dat het bestand via de maste gaat. Dit is handig als u prive ip-adressen heeft toegewezen aan de slaves en de slave niet toegankelijk zijn vanaf de buitenwereld."; 
// Normally, when downloading files, the master creates a temporary session, and then redirects the browser directly to the slave. This is to save the bandwidth, since otherwise, the files are pointlessly have to go through the master. If you enable this, hyperVM will instead route the file via the master itself. This is useful if you have given private ips for slaves, and the slaves are not accessible from the outside world.
$__information['updateform_login_options_pre'] = "[b]Let op[/b]: De time-out sessie kan niet minder zijn dan honderd. Wanner lager word ingesteld zal het automatisch ingesteld worden op honderd."; 
// Note: session timeout cannot be less than 100 and if less, will be automatically set to 100.
$__information['resourceplan_change_pre'] = "[b]Let op[/b]: Wanneer hier de waarden worden gewijzigt, dan zal elk account die dit pakket gebruikt worden bijgewerkt met de nieuwe waarden. Klik <url:a=updateForm&sa=account>hier</url> om te zien welke accounts aan dit pakket vast zitten."; 
// Note: If you change the values here, every account that uses this plan will be updated with the new values. Click <url:a=updateForm&sa=account>here to see the accounts configured on this plan</url>
$__information['lxbackup_updateform_backup_pre'] = "Het back-up bestand zal verschijnen in de __backup map van uw klant. Deze kunnen geopend worden door te klikken op het tabblad 'Bestands Beheer'. Om een back-up terug te plaatsen, dan moet deze eerst worden geupload naar de server met behulp van het tabblad [b]uploaden[/b]. Er kan direct,  http-url of een FTP-server geupload worden. Klik daarna op het pictogram van de [b]map[/b] rechts op het [b]herstellen van bestand[/b] kader en selecteer het bestand dat moet worden terug gezet. Klik vervolgens op [b]start restore process[/b]. Houd er rekening mee dat <%program%> back-up een hi&euml;rarchi is. Als er een back-up van een bepaalde bron word gemaakt, dan is alles dooaronder er automatisch bij inbegrepen. Dus als er een back-up van admin gemaakt wordt, dan hoeven er geen back-ups van klanten afzondelijk gemaakt te worden."; 
// The backup file will appear in the __backup directory of your client area. You can access it by clicking on the 'File Manager' Tab. To restore a backup, you can first upload it to the server using the [b] upload [/b] tab. You can upload directly or from an http url or an ftp server. Then come here, and click on [b] directory [/b] icon on the right in the [b] restore [/b] form, and it will allow you to select the particular file. Then click on [b] start restore process [/b]. Please note that <%program%> backup is heirarchical. If you take backup of a particular resource, everything under it is automatically included. Thus if you take backup of admin, then you need not take backups of clients under you separately.
$__information['phpini_updateform_edit_admin_pre'] = "Om Kloxo de php.ini volledig te laten beheren dan zal [b]PHP configuratie[/b] ingeschakeld moeten zijn. Houd er rekening mee dat uw oude php.ini wordt overschreven. Om de oude php.ini te herstellen schakel dan [b]PHP configuratie[/b] uit en doe een update. Het is aanbevolen om de configuratie volledig aan Kloxo over te laten. Wanneer er een speciale functie nodig is stel dan een vraag in het forum."; 
// You have to enable the [b] Manage Php Configuration [/b] flag to let Kloxo manage your php.ini completely. Please note that your old php.ini will be overwritten. To restore your old php.ini, just disable [b] Manage Php Configuration [/b] and update. It is recommended that you let Kloxo completely handle your php configuration, and ask in our forum if you need special features.
$__information['client_updateform_wall_pre'] = "[b]Let op[/b]: Het bericht zal alleen worden verzonden naar uw directe onderliggende klanten (��n niveau, inclusief dit account), die een contact e-mail adres hebben ingesteld."; 
// Note: The Message will only be sent to your direct children (one level, including this account) who has a contact email set.
$__information['ffile_updateform_upload_pre'] = "Wanneer er meerdere bestanden/mappen tegelijk moeten worden geupload, maak er een zip bestand van en upload het zip bestand. In bestands beheer kan het bestand uitgepakt worden naar de desgewenste locatie."; 
// If you want to upload multiple files/directories, zip them up and upload; you can unzip the archives from inside the file manager.
$__information['dskshortcut_a_list__pre'] = "Om een pagina toe te voegen aan favorieten klik op de link [b] toevoegen aan favorieten [/b] die rechts bovenaan elke pagina staat. Elke snelkoppeling krijgt de parameter met de naam [b] volgorde-id [/b]. Na het toevoegen van de snelkoppeling kan er bij het [b] bewerken van favorieten [/b] de volgorde worden aangepast. Door op elke snelkoppeling een geschikt [b] volorde-id [/b] toe te passen, kunt u de lijst op elke gewenste manier ordenen. Ook de naam van de link kan aangepast worden naar een meer persoonlijk herkenbare naam. De werkelijke favorieten lijst op het linkerpaneel zal precies de volgorde weerspiegelen die hier zichtbaar is."; 
// To add a page to the favorites, click on the [b] add to favorites [/b] link that appears on the top right. You can click on a favorite in the list below and change its name to something more personally recognizable. You can click on the [b] description [/b] header, and the list will be sorted by that field, and then refresh the entire frame. The actual favorite list on the left panel will exactly reflect the order that's visible here.
$__information['ticketconfig_updateform_ticketconfig_pre'] = "De mailgate is een account waaruit <%program%> e-mails zal downloaden met een bepaalde interval en zal worden geparseerd en toegevoegd aan de helpdesk. Bij het verzenden van e-mails zal <%program%> het e-mail adres gebruiken dat hiervoor is ingesteld. Het e-mail adres is in de vorm [b]account@domain.com[/b]. De Server is de pop server waarvan de e-mails gedownload worden. [b]server.com[/b]. Wanneer het selectievakje [b]gebruik ssl[/b] is aangevinkt, dan zal de e-mail worden gedownload via pop3-ssl op poort 995. Het is altijd aanbevolen dat er van ssl gebruik wordt gemaakt. Er moet wel voor gezorgd worden dat de externe mail server pop3-ssl ondersteund op poort 995."; 
// The mailgate is an account from which <%program%> will download mails at particular intervals, and will be parsed and added to the helpdesk. When sending out mails, <%program%> will send the mails as originating from the address you configure. The address is of the form [b] account@domain.com [/b]. Server is the pop server from which to download the mails. [b] server.com [/b] . If you check the [b] use ssl [/b] box, then the mail will be downloaded over pop3-ssl, at port 995. It is always recommended that you use ssl, but you will need to make sure that the remote mail serer does support pop3-ssl service at port 995.
$__information['updateform_mysqlpasswordreset_pre'] = "Dit mag alleen worden gebruikt wanneer je het root-wachtwoord kwijt bent. Onder normale omstandigheden is het wachtwoord aan te passen door <url:a=list&c=dbadmin>hier</url> (database admin). Wees geduldig, want dit kan een tijdje duren voordat het is voltooid. Dit zal het mysql root-wachtwoord resetten door de skip-grant-tables uit te voeren. Wanneer dit niet werkt log dan in op ssh en voer de volgende commando in .../bin/common/misc/reset-MySQL-root-password.php"; 
// This should only be used if you have lost the root password. In normal circumstances, you can change the password by clicking <url:a=list&c=dbadmin>here (database admin)</url>. Please be patient as this will take a while to finish. This will reset the mysql root password by running it with the skip-grant-tables option. If this doesn't work, please login through ssh and run the ../bin/common/misc/reset-mysql-root-password.php
$__information['updateform_pserver_s_pre'] = "Dit is de Server groep voor deze doorverkoper. Hier wordt de lijst van servers getoond die de doorverkoper kan gebruiken bij het aanmaken van klant. Dat wil zeggen, dat de doorverkoper uit een lijst van toegewezen servers kan kiezen en een klant daar aan kan toewijzen."; 
// This is the Server Pool for this reseller. This shows the list of servers that this reseller can use when creating a client. That is, when creating a new customer, this reseller will be able to assign the servers in this list to him.
$__information['general_updateform_disableper_pre'] = "Dit is het gebruiks percentage waarop het account wordt uitgeschakeld. De normale waarde is 110%. Er komen waarschuwingen wanneer de quota 90,100 en 110% heeft bereikt."; 
// This is the percentage of usage at which the account will be disabled. The normal value is 110%. You will be given warnings when the quota reaches 90,100,110%.
$__information['updateform_ftp_conf_pre'] = "Wanneer [b]bewaar geen kopie[/b] is ingeschakeld, dan word het lokale bestand verwijderd. Dit kan gebruikt worden wanneer er ruimte bespaard moet worden op het account."; 
// If you enable [b] dont keep local copy [/b], the local file be deleted. You can use this if you want to save space in your account.
$__information['vv_updateform_skin_logo_pre'] = "Om te voorkomen dat ondeliggende account het logo kunnen aanpassen, schakel dan 'kan logo aanpassen' uit in de machtigings instellingen."; 
// To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings. 
$__information['pserver_updateform_information_pre'] = "De FQDN is een zeer belangrijk veld en er moet een domein naam worden ingevoerd die voor de specifieke machine makkelijk op te lossen is. Na het instellen van de FQDN-naam zal hyperVM die waarde gebruiken voor alle verdere netwerkcommunicatie. Wanneer de FQDN hier four is ingesteld, dan zal de netwerk communicatie tussen master en slave mislukken. Laat het veld leeg om hyperVm het eerste ip-adres op de server te gebruiken voor communicatie. Stel de FQDN in op een hostnaam waarop deze machine vanaf overal te bereiken is."; 
// FQDN is a very important field and it should be set to a domain name that will properly resolve to this particular machine. Once you set the FQDN, hyperVM will use that value for all further network communication, and if the FQDN set here is wrong, then network communication between the master/slave would fail. If you leave it blank, hyperVM will use the first ipaddress on this server for communication. Set FQDN to a hostname using which you can access this machine from everywhere.
$__information['pserver_addform__pre'] = "Bij een versie installatie van een slave server is het wachtwoord admin. Het is sterk aanbevolen dat de servers worden toegevoegd met het invoeren van hun naam in plaats van hun ip-adres. De Server moet vanaf de master toegankelijk zijn met behulp van de specifieke naam die die hier is opgegeven; bijvoorbeeld server.domain.com. De uitgebreide beschrijving is een tekenreeks die kan worden gebruikt om deze server te beschrijven en is zichtbaar in chooser vakken."; 
// If you have freshly installed a slave server, the password is admin. It is strongly recommended that you add servers by their name rather than by their IP. The Server Should be accessible from the master using the particular name you supply here, for instance, server.domain.com. The verbose-identifier is a string that can be used to describe this server, and will be visible in chooser boxes.
$__information['updateform_upload_logo_pre'] = "- Laat de velden leeg om het huidige logo te verwijderen. Standaard logo's zullen dan weer getoond worden.<br />".
											   "- Schakel 'kan logo aanpassen' uit in de permissies om te voorkomen dat onderliggende klanten het logo aanpassen.<br />";
// Leave the fields blank to reset the logos to default images. To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings.
$__information['xen_restart_message'] = "[b]Let op[/b]:De Xen VM moet opnieuw opgestart worden voordat de veranderingen effect zullen heben. Bij OpenVZ worden veranderingen meteen aangepast zonder opnieuw op te hoeven starten ";
// Please note that you have to restart the Xen VM for the changes to take affect. This is necessary only for Xen VMs. OpenVZ changes are affected immediately.</font>
$__information['updateform_createtemplate_pre'] = "Dit zal de VPS converteren naar een os sjabloon die gebruikt kan worden voor het aanmaken van volgende virtual private servers. De erste drie woorden van het nieuwe os sjabloon moeten correct overeenkomen met de de distributie en versie en worden dan automatisch gegenereerd van het os sjabloon op deze server. De vierde invoer kan zelf ingevuld worden voor het aanduiden van het type os afbeelding die hier is vertegenwoordigt.";
// This will convert this vps into an ostemplate, which can be used to create further vpses. The initial three words of the new os template has to properly reflect the distro and version, and thus they are automatically generated from the Os template of this vps. You can supply the fourth string, and it can denote the type of OS Image this represents.
$__information['updateform_importvps_pre'] = "Als deze server gebruikt moet worden als onderdeel van een een andere HyperVM master, klik dan op <url:a=updateform&sa=importhypervmvps> Import HyperVM VPS </url> om [b]alle[/b] gegevens transparant te importeren. Dit moet wanneer er geprobeerd word om een slaaf te migreren van de ene naar de andere master of om te verplaatsen. Dit hoeft alleen gedaan te worden wanneer wanneer er geprobeerd wordt om een VPS van een server te importeren die eerder geen conrole paneel had.";
// If this server used to be part of an another hyperVM master, then you should use <url:a=updateform&sa=importhypervmvps> Import HyperVM VPS </url>, which will import [b] ALL [/b]  data transparently. You should that one if you are trying to migrate a slave from one master to another or trying to move the master from one server to another. You should use this one, only if you are trying to import vps from a server which had no control panel earlier.
$__information['updateform_clonevps_pre'] = "Door <url:a=updateform&sa=createtemplate>hier</url> te klikken wordt een VPS in een os sjabloon geconverteerd zodat er een clone gemaakt kan worden van een VPS. Nadien kan het os sjabloon verwijderd worden door het ingebouwde os sjabloon beheer.";
// You can clone a vps by first converting it into an ostemplate by <url:a=updateform&sa=createtemplate> Clicking Here </url>, and then using that to create a vps. After that you can delete the ostemplate using the in built ostemplate manager.
$__information['updateform_macaddress_pre'] = "Het is alleen nodig om de eerste vijf velden in te vullen van het mac adres. Het laatste veld wordt automatisch voor elk ethernet toestel gegenereerd als 01, 02... De VPS moet opnieuw opgestart worden voordat de veranderingen effect hebben.";
// You need to supply only the first 5 fields of the macaddress. The last is automatically generated for each ethernet device as 01, 02... You need to reboot the VPS for the change to take effect.
$__information['updateform_importhypervmvps_pre'] = "Dit is vooral bedoeld om een slave te verplaatsen van de ene naar de andere master. Ga eerst naar [b] admin home -> servers -> server (slave) home -> vps gegevens opslaan [/b] op de [b]oude[/b] master en sla de gegevens op de slave. Na het opslaan van de gegevens kan de VPS ge&iml;mporteerd worden vanaf deze slave.";
// This is primarily meant for moving a slave from one master to another. You should first go to [b] admin home -> servers -> server (slave) home -> save vps data [/b] on the [b] OLD [/b]  master and save the data to this slave. After you save the data, you can import the vps from this slave.
$__information['updateform_savevpsdata_pre'] = "Dit is vooral bedoeld om een slave te verplaatsen van de ene naar de andere master. Draai dit op de oude master zodat de gegevens op de slave worden opgeslagen. Dan door op de [b]nieuwe[/b] master kan alles ge&iuml;mporteerd worden vanaf [b] admin home -> servers -> server (slave) home -> import hyperVM VPS [/b]";
// This is primarily meant for moving a slave from one master to another. Run this on the old master, so that the data will be saved to the slave. Then from the [b] NEW [/b] master, you can import everything by going to [b] admin home -> servers -> server (slave) home -> import hyperVM VPS [/b]
$__information['vps_updateform_rebuild_pre'] = "<font color=red> Let op: De bestaande VPS wordt volledig verwijderd. Alle aanwezige gegevens zullen verloren gaan.</font> ";
// <font color=red> Note: The existing Vps will be completely destroyed and built anew. You will lose all data that is currently in there. </font>
$__information['ippoolextraip_a_addform__pre'] = "Dit zijn de extra ip adressen die geldig zijn in de ip adressen in de ip groep.";
// These are the extra ip addresses that will be counted into the ips in the ippool.
$__information['ippoolexceptionip_a_addform__pre'] = "Dit is de lijst van ip adressen die worden genegeerd bij inschrijving in een ip groep.";
// This is the list of IP addresses that will be ignored when assigning ips from this ippool.
$__information['ippoolpingip_a_list__pre'] = "Bij de laatste stap zal HyperVM het ip adres pingen voordat het ip adres aan een VPS word toegewezen. Is het pingen geslaagd dan wordt het beschouwd als reeds toegewezen en hyperVM zal het ip adres registreren. Een ip adres wordt hier getoond wanneer een ip adres buiten de HyperVM cluster wordt gebruikt door een host en is dus niet bruikbaar. Is het ip adres vrij dan kan het hier verwijderd worden zodat het weer terug geplaatst word in de ip groep.";
// HyperVM will ping the Ipaddress at the last step before it assigns the IP to the vps. If it can ping the IP, then it is considered as already allocated and hyperVM will record the IP here. If an IP is listed here, then it means that some host outside of the hyperVM cluster already uses this IPaddress, and so this IP is unusable. If you are sure that an IP is free, you can delete it from this list, which would put the IP back in the IPpool.
$__information['vps_updateform_mainipaddress_pre'] = "Hier wordt de ip adres configuratie met het hoofd ip adres als eerste volledig opnieuw gerangschikt. Dit is handig voor programma's die bepaalde ip adressen als hoofd ip adres nodig heeft voor de licenties om goed te werken. Houd er rekening mee dat de VPS opnieuw opgestart moet worden voordat de veranderingen effect hebben. Ook wanneer er een ander ip adres wordt toegevoegd, dan zal het hoofd ip adres opnieuw moeten worden ingesteld.";
// This will completely rearrange your ipaddress configuration, with the main ipaddress as the first one. This is useful for programs that need certain ipaddress as the main one for the licenses to work properly. Please note that you have to restart your vps for this to work properly. Also, if you add another ip address, you will have to reset your main ipaddresses again.
$__information['addform_normal_pre'] = "Om meerdere ip adressen toe te voegen, gebruik dan een komma als scheidingsteken.";
// To add multiple Ipaddresses, use comma as the separator.
$__information['updateform_livemigrate_pre'] = "OpenVZ livemigrate heeft een fout, doordat de ssh poort op 22 ingesteld moet worden. Ga naar [b] server home -> ssh configuratie [/b] en stel de poort in op 22 en voer de migratie uit. Na de migratie kan de poort weer terug gezet worden";
// Openvz livemigrate has a bug, which needs the ssh port on the destination to be set to 22. Go to [b] server home -> ssh config [/b] and set it to 22 and then migrate. After that you can switch the port back.
$__information['client_addform_customer_pre'] = "[b]Let op[/b]: Maak alleen een klant aan wanneer deze meer dan &euml;&euml;n VPS bezit. Anders is een VPS een complete login waarop je kan inloggen als vps.vm en wachtwoord. Is er al een klant aangemaakt ga dan naar [b]vps home -> geavanceerd -> verander eigenaar[/b] en verplaats hem terug naar de admin. Ga dan naar [b] vps home -> geavanceer -> welkomst bericht opnieuw versturen[/b] om de nieuwe login informatie te versturen. Om meer dan &euml;&euml: VPS voor een klant te hebben, maak dan een klant aan met ongelimiteerde voorzieningen. Schakel [b]kan limiet aanpassen[/b] en [b]kan VPS toevoegen[/b] uit in de permissies. Dit betekent dat de klant alleen toegang heeft to zijn VPS's, maar kan geen limieten aanpassen en VPS's toevoegen.";
// PLEASE NOTE: Create Customers ONLY if they have more than one vps. Otherwise a VPS is a fully complete login and you can login as vps.vm and the password. If you have already created customers, then go to [b] vps home -> advanced -> change owner [/b] and move them back to admin, then go to [b] vps home -> advanced -> resend welcome message [/b] to send them the new login information. To have more than one vps in a client, create a client with unlimited resources, and then disable his [b] can change limit [/b] and [b] can add vps [/b] permissions. This means that he will only be able to access his vpses, and not able to change their resource limits, nor add new vpses.
$__information['pserver_updateform_centralbackupconfig_pre'] = "Interne netwerk ip adressen worden gebruikt bij het nemen van back-ups om te voorkomen dat de belangrijkste netwerken verstopt raken. Sommige DC's bieden een apart intern particulier netwerk en dit kan worden gebruikt bij het maken van een back-up. De ip die hier opgegeven zal worden word gebruikt door de backup server om te verbinden met deze node, wanneer er een backup gemaakt wordt van de VPS. Laat het veld bij twijfel leeg.";
// Internal Network Ipaddress is used when taking backups to avoid congesting the main network. Some DCs will provide separate internal private network, and this can be used when taking backup. The ip you provide here will be used by the backup server to connect to this node when taking backup of the vps. If you are unsure, leave it blank.
$__information['updateform_ippool_pre'] = "HyperVM houdt sommige interne configuraties om  de belasting van de ip groep beheer te verminderen. Sommige ip addressen zijn dan niet beschikbaar voor korte perioden, zelfs wanneer ze vrij zijn. Door hier te klikken word de complete interne database geleegd. Dit is een volkomen onschadelijk actie, en klik hier wanneer er zich problemen voordoen met de ip groep.";
// HyperVM keeps some internal configurations so as to reduce the load of the IP Pool management. This may make some ipaddresses unavailable for short periods, even when they are free. Clicking here will completely clear the internal databases. This is a completely harmless action, and click here if you are facing any issue with ippool.
$__information['vps_updateform_fixdev_pre'] = "Dit is zeer speciale oplossing voor het probleem dat gebeurt is in centos-4.5, de upgrade die alle /dev/ posten zal verwijderen waardoor de vps onbruikbaar wordt. Dit zal verse dev invoer uitpakken naar een vps en het probleem oplossen.";
// This is very special fix for the problem that happens in centos-4.5, the upgrade to which to will remove all the /dev/ entries thereby rendering the vps inoperable. This will untar a fresh dev entry into the vps and solve the problem.
$__information['vps_updateform_recovervps_pre'] = "Recover vps zal het bestaande os sjabloon over de bestaande  vps uitpakken. Dit betekent dat als een van de systeembestanden beschadigd waren, ze zullen worden hersteld. Aangezien alleen de systeembestanden worden bijgewerkt en naar de gegevensbestanden niet wordt gekeken is dit een veilige manier om een gebroken vps te herstellen.";
// Recover vps will untar your existing ostemplate over your vps. This means that if any of the system files were corrupted, they will be recovered. Since, only the system files are updated and your data files are left untouched, this is a safe means to fix a broken vps.
$__information['vps_updateform_installkloxo_pre'] = "<font color=red>Let op:</font> Een installatie van Kloxo is in principe een volledige reconstructie van de vps met een vers os sjabloon die kloxo heeft. Dit betekent dat het huidige systeem volledig zal worden verwoest en opnieuw word opgebouwd. De Url voor kloxo is https://ip:7777 en controle paneel login/wachtwoord voor kloxo is admin/admin.";
// <font color=red> Note: </font>  Installation of Kloxo basically involves a complete rebuild of the vps with a fresh ostemplate containing kloxo, and thus your current system will be completely destroyed and rebuilt. The Url for kloxo is https://ip:7777 and CP login/password for kloxo is admin/admin.
$__information['general_updateform_kloxo_config_pre'] = "De installApp kan voor alle VPS's op &euml;&euml; centrale locatie gehost worden. HyperVM zal kloxo zo configureren dat het automatisch de externe url als locatie voor de installApp toepassingen zal gebruiken. Dit bespaart 1 GB per vps. De url is van het formulier http://url/application.tar.gz waar het bestand moet bestaan.";
// You can host the installApp for all your vpses in a central location. HyperVM will configure kloxo so that it will automatically use the remote url as the location for the installApp applications. This will save you 1GB per vps. The url is of the form where http://url/application.tar.gz file should exist.
$__information['general_updateform_browsebackup_pre'] = "Het is de eigenaar toegestaan door de backup te bladeren en deze individueel te herstellen. Om deze functie te hebben dan moeten de [b]central-backup-servers[/b] ge&iuml;ntergeerd worden in de cluster. Zorg er ook voor dat de slave id parameters worden geleverd in de backup server configuratie. Dit is de slave naam van de backup server in de cluster. Dit betekent dat HyperVM de VPS eigenaar toelaat om door zijn eigen backup te bladeren en individuele bestanden te herstellen. Klik <a href=http://lxlabs.com/software/hypervm/backup/ target=_blank>hier</a> voor meer informatie.";
// Browse Backup allows a vps owner to go through every file in his backup, and restore them individually. To have this feature, the [b] central backup-servers [/b]  should be integrated into the cluster, and you also have to make sure that you supply the [b] slave-id [/b] parameter, in the backup-server configuration which is the slave-name of the backup-server in the cluster. This means that hyperVM will allow the vps owner to browse his own backup, and restore individual files. <a href=http://lxlabs.com/software/hypervm/backup/ target=_blank> Click here </a> for more info.
$__information['vps_addform_openvz_pre'] = "Een VPS is een volledig zelfstandig inlog systeem. Er hoeft geen aparte klant aangemaakt te worden; de eigenaar van de VPSkan op het controle paneel inloggen door zijn VPS gebruikernaam en wachtwoord te gebruiken. Er moet wel een nieuwe klant aangemaakt worden wanner de klant meer dan &euml;&euml;n VPS heeft. Een VPS eigenaar is een compleet klanten systeem met zijn eigen helpdesk, login geschiedenis, enz.";
// A VPS is a fully self contained login system. You need not create a separate client; the owner of the vps can login to the Control Panel using the vps name and password. You should create a client only if he has more than one vps. A vps owner is a complete client system with its own help desk, login history etc.
$__information['updateform_deleteorphanedvps_pre'] = "Hier is het mogelijk om [b]zwevende VPS's[/b] te verwijderen. [b]Zwevende VPS's[/b] zijn VPS's waarvan de bovenliggende node niet langer beschikbaar zijn in de database van HyperVM. Dit verwijdert alleen de VPS's van de HyperVM database. Deze situatie kan zich voordoen wanneer een node totaal niet beschikbaar is en de node verwijderd is door [b]server geforceerd verwijderen[/b] te hebben gebruikt.";
// This will allow you to remove [b]  Orphaned VPSes [/b] . [b] Orphaned VPSes [/b]  are VPSes whose parent node is no longer present in hyperVM's database. This will just remove the vpses from hyperVM's database. This situation can arise, if a node becomes completely inaccessible, and you have removed the node using [b] force delete server [/b]. And then you can delete the VPSes on the node using this feature.
$__information['vps_addform_xen_pre'] = "Een VPS is een volledig zelfstandig inlog systeem. Er hoeft geen aparte klant aangemaakt te worden; de eigenaar van de VPSkan op het controle paneel inloggen door zijn VPS gebruikernaam en wachtwoord te gebruiken. Er moet wel een nieuwe klant aangemaakt worden wanner de klant meer dan &euml;&euml;n VPS heeft. Een VPS eigenaar is een compleet klanten systeem met zijn eigen helpdesk, login geschiedenis, enz.";
// A VPS is a fully self contained login system. You need not create a separate client; the owner of the vps can login to the Control Panel using the vps name and password. You should create a client only if he has more than one vps. A vps owner is a complete client system with its own help desk, login history etc.
$__information['kloxo_show__pre'] = "Wanneer dit voor de eerste keer wordt uitgevoerd, zorg ervoor dat de vps via het configuratiescherm opnieuw opgestart word zodat hyperVM de nodige veilige toegangs parameters kan instellen.";
// If you are running this for the first time, make sure that you reboot the vps through Control Panel once, so that hyperVM can setup the necessary secure access parameters.
$__information['emailalert_addform__pre'] = "Dit zijn de extra e-mail adressen die door de poort monitoring systeem worden gebruikt wanneer er een dienst uitvalt. Het huidige contact e-mail adres is te vinden onder het tabblad [b]informatie[/b] ";
// These are the extra email addresses that are also intimated by the port monitoring system when a service goes down. Your actual contact email can be found under the [b] information [/b] tab
$__emessage['blocked'] = "Uw adres is geblokkeerd.";
// Your address is blocked
$__emessage['no_server'] = "Kan geen verbinding maken met de Server."; 
// Could not connect to the Server.
$__emessage['set_emailid'] = "Stel uw E-mail ID correct in "; 
// Please Set Your EmailId Properly
$__emessage['no_socket_connect_to_server'] = "Kan geen verbinding maken met de server [%s]. Dit is hoogst waarschijnlijk te wijten aan onderliggende netwerk probleem. Zorg ervoor dat de server toegankelijk is vanaf dit bepaalde knooppunt door [b] telnet slave-id 7779 [/b] te laten draaien.";
//Could not Connect to the server [%s]. This is most likely due to underlying network problem. Make sure that the server is accessible from this particular node by running [b] telnet slave-id 7779 [/b]
$__emessage['restarting_backend'] = "De backend word opnieuw opgestart. Probeer over 30 seconden nog een keer."; 
// Restarting the backend. Please try again after 30 seconds.
$__emessage['quota_exceeded'] = "Quotum overschreden voor [%s]"; 
// Quota Exceeded for [%s]
$__emessage['license_no_ipaddress'] = "Het openbare ip-adres [%s] van deze server is niet gevonden in de licentie repository. Neem contact op met Lxlabs verkoop of de verkoper om een licentie te maken voor deze server. "; 
// The public ipaddress [%s] of this server was not found in in the license repository. Please contact Lxlabs sales or your reseller to create a license for this server. </a>
$__emessage['ssh_root_password_access'] = "U heeft de wachtwoord gebaseerde toegang tot root op deze server niet uitgeschakeld. Wachtwoord gebaseerd toegang tot de root is niet nodig aangezien u ssh gemachtigd sleutels via uw hypervm zelf kan beheren. Klik <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig>hier</url> voor het configureren van uw ssh server."; 
// You have not disabled password based access to root on this server. Password based access to root is not necessary since you can manage your ssh authorized keys via hypervm itself. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Click here </url> to configure your ssh server.
$__emessage['already_exists'] = "De bron van naam [%s] bestaat al."; 
// The resource of name [%s] already exists.
$__emessage['lxguard_not_configured'] = "Lxguard voor deze server is niet geconfigureerd. Klik <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>hier</url> om LXguard te configureren. Het is belangrijk dat er begrepen wordt wat het doet. Lxguard is van cruciaal belang voor de beveiliging van de server. Het kan op hetzelfde moment ook een eigen IP-adres blokkeren zodat er geen toegang tot de server verkregen kan worden. Dit kan zeer frustrerend zijn wanneer niet bekend is wat er gebeurt."; 
// Lxguard for this server is not configured. Please <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Click here to configure Lxguard </url> since it is very important that you understand what it does. Lxguard is critical for the security of your server, at the same time, it can block your own IPaddress from accessing the server, which can be frustrating if you don't know what's happening.
$__emessage['root_cannot_extract_to_existing_dir'] = "De naam van de opgegeven locatie bestaat al. De root gebruiker kan geen bestand uitpakken naar een bestaande map. Geef de naam op van een map die niet in het systeem bestaat."; 
// Directory you provided already exists. Root user cannot extract archive into an existing directory. Please provide the name of a directory that doesn't exist in the system.
$__emessage['no_imagemagick'] = "Er is geen imagemagick aanwezig in het systeem. Imagemagick kan ge&iuml;nstalleerd worden door [b] yum -y install imagemagick [/b] in een terminal venster in te voeren.";
//There is no imagemagick in the system. You can install imagemagick by running [b] yum -y install imagemagick [/b].
$__emessage['warn_license_limit'] = "De licentielimiet voor [%s] is bijna bereikt. Wanner het systeem [%s] over zijn limiet gaat dan zal de interface stoppen met werken en kan het systeem niet meer beheerd worden. Klik <url:o=license&a=show>hier</url> om de licentie bij client.lxlabs.com te updaten."; 
// You are very close to your license limit for [%s]. If the system goes over limit for [%s] the interface will stop working and you won't be able to manage your system. Please increase your license at client.lxlabs.com and update by <url:o=license&a=show> clicking here </url>
$__emessage['file_already_exists'] = "Het bestand [%s] bestaat al."; 
// The file [%s] already exists.
$__emessage['contact_set_but_not_correct'] = "De contact informatie lijkt geen geldig e-mailadres te zijn. Klik <url:a=updateform&sa=information>hier</url> om het aan te passen."; 
// Your Contact Information doesn't appear to be a valid email address. Click <url:a=updateform&sa=information> here to fix it.</url>
$__emessage['contact_not_set'] = "De contact informatie is niet goed ingesteld. Klik <url:a=updateform&sa=information>hier</url> om het aan te passen. "; 
// Your Contact Information is not set properly. Click <url:a=updateform&sa=information> here to fix it. </url>
$__emessage['you_have_unread_message'] = "Er zijn [%s] ongelezen bericht(en). Klik <burl:a=list&c=smessage>hier</burl> om ze te lezen."; 
// You have [%s] Unread Message(s). click <burl:a=list&c=smessage> here  to read it. </burl>
$__emessage['you_have_unread_ticket'] = "Er zijn [%s] ongelezen ticket(s). Klik <burl:a=list&c=ticket>hier</burl> om ze te lezen."; 
// You have [%s] Unread Ticket(s). click <burl:a=list&c=ticket> here  to read it. </burl>
$__emessage['security_warning'] = "Het wachtwoord is nu ingesteld met een automatisch gegenereerd wachtwoord dat een ernstige bedreiging vormt. Wijzig deze onmiddellijk door <url:a=updateform&sa=password>hier</url> te klikken. "; 
// Your password is now set as a generic password which constitutes a grave security threat. Please change it immediately by <url:a=updateform&sa=password> clicking here. </url>
$__emessage['ssh_port_not_configured'] = "De ssh port voor deze server is niet ingesteld. Het is een goed idee om het te veranderen naar iets anders dan de standaard 22. Klik <url:a=show&o=sshconfig>hier</url> om het aan te passen. Wanneer poort 22 wel behouden moet worden, maar niet steeds dit bericht krijgen ga dan naar de pagina en stel poort 22 geforceerd in. De waarschuwing wordt dan niet opnieuw weergegeven."; 
// The ssh port for this server is not set. It is a good idea to change it to something other than the default 22. Please  <url:a=show&o=sshconfig> click here to change:</url>. If you want to keep the ssh port to 22 and still avoid this message, go to the page, and set it forcibly to 22, and the warning will not be displayed again.
$__emessage['system_is_updating_itself'] = "Het systeem is op dit moment zichzelf aan het upgraden, daarom kunnen er nu voor een paar minuten geen wijzigingen worden aangebracht. Alle lees acties werken wel normaal."; 
// The system at this point is upgrading itself, and thus you won't be able to make any changes for a few minutes. All read actions work normally though.
$__emessage['system_is_locked'] = "Iemand is een systeem-modificatie-actie op dit bepaald object gestart en die draait nog steeds. Er kunnen pas wijzigingen worden aangebracht nadat de actie is afgerond. Alle lees acties werken wel normaal."; 
// Someone has initiated system-modification-action on this particular object which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.
$__emessage['system_is_locked_by_u'] = "Er is een systeem-wijziging-actie gestart die nog steeds draait. Er kunnen pas wijzigingen worden aangebracht nadat de actie is afgerond. Alle lees acties werken wel normaal."; 
// You have initiated a system-modification-action which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.
$__emessage['smtp_server_not_running'] = "HyperVM kan geen verbinding maken met een SMTP-server op deze server. Dat betekent dat HyperVM niet in staat is in het verzenden van e-mails. Dit is zeer kritisch aangezien HyperVM de gezondheid controleert van de hele cluster en een e-mail naar de admin verstuurd wanneer er problemen ontstaan. Er moet voor gezorgd worden dat de SMTP-service wordt uitgevoerd op deze server. Zodra de SMTP-service opnieuw is opgestart zal het vijf minuten duren voordat dit foutbericht verdwenen is. Dit is omdat HyperVM &euml;&euml;n keer per minuten controleert of deze dienst aanwezig is."; 
// hyperVM could not connect to an smtp server on this server. That means that hyperVM will not able to send out any mails. This is very critical since hyperVM monitors the health of the entire cluster and sends email to the admin if there is any problem. You should make sure that the smtp service is running on this server. Once you restart the SMTP service, please wait 5 minutes for this error message to disappear, since hyperVM checks for the service availability only once every 5 minutes.
$__emessage['template_not_owner'] = "U bent niet de eigenaar van deze sjabloon."; 
// You are not the Owner of this Template
$__emessage['ipaddress_changed_amidst_session'] = "IP-adres is gewijzigd tijdens een sessie. Dit is mogelijk sessie kaping."; 
// IP Address Changed Amidst Session. Possible Session Hijacking.
$__emessage['more_than_one_user'] = "Meer dan ��n gebruiker is ingelogd op dit account. Klik <burl:a=list&c=ssession>hier</burl> voor een overzicht van aangemelde gebruikers. "; 
// More than one user is logged in this account. Click <burl:a=list&c=ssession>here to see list of logins. </burl>
$__emessage['login_error'] = "Inloggen is misluk!"; 
// Login Unsuccessful
$__emessage['file_exists'] = "bestand(en) [%s] bestaat reeds. Niet overschrijven..."; 
// file(s) [%s] Exists. Not Pasting...
$__emessage['cannot_unzip_in_root'] = "Er kunnen geen zip bestanden uitgepakt worden naar de root map. Gelieve een andere naam op te geven voor de map waarnaar het bestand uitgepakt dient te worden."; 
// You cannot unzip files into the root. Please specify a directory and unzip into that.
$__emessage['nouser_email'] = "De e-mail komt niet overeen met de gebruikers contact e-mail adres."; 
// The Email doesn't match User's Contact Email Address
$__emessage['session_expired'] = "Sessie is verlopen"; 
// Session Expired
$__emessage['e_password'] = "Onjuist Wachtwoord."; 
// Password Incorrect
$__emessage['is_demo'] = "[%s] is uitgeschakeld in de demo versie."; 
// [%s] is Disabled in Demo Version.
$__emessage['user_create'] = "Gebruiker [%s] kon niet aangemaakt worden. Probeer een andere naam."; 
// User [%s] Could not be Created. Please try a different Name
$__emessage['switch_done'] = "Schakelen tussen de servers is uitgevoerd op de achtergrond. U ontvangt een mail wanneer de overstap voltooid is."; 
// Switching the Servers has been run in the background. You will be sent a mail when the switch is complete.
$__emessage['mis_changed'] = "Weergave configuratie is succesvol gewijzigd."; 
// Display Configuration successfully changed.
$__emessage['password_sent'] = "Wachtwoord is opnieuw ingesteld en succesvol verzonden."; 
// Password was reset and sent successfully.
$__emessage['added_successfully'] = "[%s] is succesvol toegevoegd."; 
// [%s] was added successfully.
$__emessage['backup_has_been_scheduled'] = "De backup gebeurt nu op de achtergrond. U ontvangt een mail aan uw contact e-mail wanneer de backup voltooid is."; 
// The backup is now happening in the background. You will receive a mail at your contact email when it is done.
$__emessage['update_scheduled'] = "Update wordt nu op de achtergrond uitgevoerd. U kunt deze pagina vernieuwen om te zien of de update correct is voltooid.";
//Update is now running in the background. You can refresh this page to see if the update has completed properly.
$__emessage['restore_has_been_scheduled'] = "Het opnieuw opslaan gebeurt nu op de achtergrond. U ontvangt een mail op uw contact e-mail wanneer het opslaan is voltooid."; 
// The Restore is now happening in the background. You will receive a mail at your contact email when it is done.
$__emessage['old_kloxo_found'] = "Er is een Kloxo installatie bestand gevonden op de VPS. Dit betekent dat Kloxo al is ge&iuml;nstalleerd. Verwijder de kloxo-install-master.sh en /usr/local/lxlabs/kloxo locaties (gebruik bestands beheer) om het opnieuw te proberen.";
// An Kloxo Installation file was found in the vps, which would mean that Kloxo is already installed. If you want me to try again, please delete the kloxo-install-master.sh and /usr/local/lxlabs/kloxo locations using the file manager.
$__emessage['a_vps_with_the_same_id_exists'] = "Een VPS met id [%s] bestaat al in het systeem. Dit betekent dat er dit van buiten hyperVM is gemaakt of omdat hyperVM tijdens een migratie is onderbroken. Het is mogelijk om handmatig in te loggen en de VPS verwijderen of gebruik de import faciliteit om de VPS in HyperVM te importeren. Onze excuse voor het ongemak.";
// A vps with the id [%s] already exists on the system. This either means this was created outside of hyperVM or else it got orphaned because hyperVM was interrupted forcibly in the midst of a migration. You can either a) Login manually and delete the vps. or b) Use our import facility to import this vps into hyperVM. Sorry for the inconvenience.
$__emessage['could_not_start_vps'] = "Het was niet mogelijk om de VPS te starten; Reden: [%s]";
// Could Not Start Vps, Reason: [%s]
$__emessage['vps_is_locked_by_another_user'] = "Ce VPS [%s] is geblokkeerd door een andere gebruiker. Dit kan komen doordat een eerdere activiteit is afgebroken omdat die te lang over het proces heeft gedaan. HyperVm heeft 15 seconden gewacht om het andere proces te be&euml;indigen. Probeer het later nog eens. ";
// The vps [%s] is locked by another user. This would also be because you had interrupted an earlier activity that would take long time to complete. HyperVM has waited 15 seconds for the other process to finish. Please try after sometime.
$__emessage['macaddress_only_five'] = "Het is alleen nodig om de eerste vijf velden in te vullen van het mac adres. Het laatste veld wordt automatisch voor elk ethernet toestel gegenereerd als 01, 02...";
// You need to supply only the first 5 fields of the macaddress. The last is automatically generated for each ethernet device as 01, 02...
$__emessage['to_use_filemanager_shut_down_xen_vm_first'] = "Het bestands beheer kan alleen gebruikt worden wanneer de virtuele machine is uitgeschakeld en het zal fungeren als een mechanisme om eventuele fouten te herstellen wanneer de server het niet bijhoud. ";
// The filemanager can be used only when the Virtual Machine is shutdown, and it will act as a mechanism to fix any issues if your server is not coming back up.
$__emessage['rebuild_time_limit'] = "Wacht voor [%s] minuten voordat er opnieuw opgebouwd wordt.";
// Please wait for [%s] minutes before you rebuild again.
$__emessage['vpsid_already_exists_on_another_server'] = "Het VPS id bestaat op een andere server.";
// The vpsid [%s] exists on another server.
$__smessage['vps_creation_in_background'] = "Virtual Private Servers worden op de achtergrond gecre&euml;erd. Vernieuw de pagina regelmatig om ze in de lijst te zien.";
// Vpses are getting created in the background. Just periodically refresh this page, and you can see them listed.
$__smessage['kloxo_installation_started'] = "De Kloxo installatie is gestart in de VPS. Het rapport HyperVM-klox_install.log is bewaard in de <b>/</b> map die te vinden is via bestands beheer.";
// Kloxo Installation has been started in the VPS. The log is kept in a file called HyperVM-kloxo_install.log in the / directory, which you can view using the File Manager

//Text in bestands beheer
//Please NOTE: The graph on the left of each file, seen after you have clicked on the disk usage , shows the usage of that file relative to the total. When the tag on the graph says "file a.tar.gz uses 10MB of 30MB", it means that the total size occupied by the all the files in the directory is 30MB, and a.tar.gz uses 10MB. This is in no way related to your total disk quota. The graph merely shows the size of one file in relation to the total used by all the files in that particular directory.
//<br>Normally, the actual disk space occupied by the directories is not shown. Click on disk space so that instead of showing the '0' or '4096' against the directory size, the listing will show the actual space occupied by the directories. Please note that this is a resource intensive process, and will take a bit of time. Also, this is a one time operation. If you want to see the disk usages again, you have to click on disk space again.
//<br>You can sort by real size by clicking on the size and then clicking on disk space 