<?php 

$driver['client'] = "sync";
$driver['mysqldb'] = "mysql";
$driver['mysqldbuser'] = "mysql";
$driver['sshauthorizedkey'] = "sync";
$driver['dbadmin'] = "sync";
$driver['mssqldb'] = "mssql";
$driver['mssqldbuser'] = "mssql";
$driver['sslcert'] = "sync";
$driver['sslipaddress'] = "sync";
$driver['anonftpipaddress'] = "__v_ftpuser";
$driver['process'] = '__v_pserver';
$driver['diskusage'] = '__v_pserver';
$driver['lxguard'] = 'sync';
$driver['lxguardwhitelist'] = 'sync';
