<?php 

$driver['hostdeny'] = "linux";
$driver['ffile'] = "linux";
$driver['dns'] = "bind";
$driver['vps'] = array("openvz", "xen", "kvm", "vmware");
$driver['pserver'] = "linux";
$driver['uuser'] = "linux";
$driver['reversedns'] = "bind";
$driver['ftpuser'] = "pureftp";
$driver['cron'] = "linux";
$driver['llog'] = "linux";
$driver['vmachine'] = "xen";
$driver['dirlocation'] = "linux";
$driver['dirlocation'] = "linux";
$driver['sshconfig'] = 'linux';
